[package]
name = "sark-client"
version.workspace = true
edition.workspace = true
description = "Simple Asynchronous Rust webKit - Client"
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
sark-core.workspace = true
dope.workspace = true
dope-net.workspace = true
dope-fiber.workspace = true
dope-gen.workspace = true
o3.workspace = true
cartel-core.workspace = true
http = "1.5.0"

[dev-dependencies]
flate2 = "1"
pin-project.workspace = true
