[workspace]
resolver = "2"
exclude = [
    "fuzz",
]
members = [
    "client",
    "core",
    "gen",
    "grpc",
    "grpc-build",
    "h2",
    "h3",
    "json",
    "protocol",
    "sark",
    "ws",
]

[workspace.package]
edition = "2024"
version = "0.13.0"
description = "the L7 layer for dope"
repository = "https://github.com/dope-rs/sark"
license = "MIT"
authors = ["inq <gofiri@gmail.com>"]

[workspace.dependencies]
cartel-core = "0.10"
cartel-gen = "0.10"
cartel-pg = "0.10"
cartel-redis = "0.10"
dope = "0.14"
dope-net = "0.14"
dope-fiber = "0.14"
dope-gen = "0.14"
dope-test = "0.14"
dope-tls = "0.18"
o3 = "0.9.2"
shin = "0.14"
pin-project = "1"
pin-project-lite = "0.2"
prost = "0.14.4"
prost-build = "0.14.4"
sark-core = { path = "core", version = "0.13" }
sark-gen = { path = "gen", version = "0.13" }
sark-h2 = { path = "h2", version = "0.13" }
sark-json = { path = "json", version = "0.13" }
sark-protocol = { path = "protocol", version = "0.13" }
sark-ws = { path = "ws", version = "0.13" }
sark = { path = "sark", version = "0.13" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = "line-tables-only"
